### ISSUE TITLE
Registre/login d'usuaris

### ISSUE THREAD

**Issue by carlotacb** [carlotacb/IssueTracker_ASW#11]

**Comment by GuillemCastro** [comment]
Login amb Google implementat a https://github.com/carlotacb/IssueTracker_ASW/commit/925f86ba3e284fe5b13851e27bb117a882d5ef22 assignació del usuari registrat a les Issues noves implementat a https://github.com/carlotacb/IssueTracker_ASW/commit/f963e925967737e9ba9357a449cdd8823ab7ecc1
