### ISSUE TITLE
Preguntes

### ISSUE THREAD

**Issue by carlotacb** [carlotacb/IssueTracker_ASW#15]
Bones Carles,

Tinc un seguit de preguntes:
1. Es necessari que al issues aparegui la imatge del usuari assignat, com al BitBucket?

2. Estic tenint problemes a la pagina del show per posar el "boto" de Resolved/Open y el dropdown de workflow, son necesaris aquests camps?

Moltes Gràcies.

**Comment by carlesf** [comment]
1. No, no ho és
2. El dropdown sí.
