### ISSUE TITLE
Diferents llistats d'issues

### ISSUE THREAD

**Issue by carlotacb** [carlotacb/IssueTracker_ASW#6]

**Comment by AleixBalletbo** [comment]
Links implementats a https://github.com/carlotacb/IssueTracker_ASW/commit/b140507432c050c00e13160d02ea8846a02f1b3c

**Comment by AleixBalletbo** [comment]
Resta de filtres implementats a https://github.com/carlotacb/IssueTracker_ASW/commit/713c1f436cae3a7093c836cefc838cb3d16ce58b
