### ISSUE TITLE
Attachments

### ISSUE THREAD

**Issue by carlotacb** [carlotacb/IssueTracker_ASW#7]

**Comment by GuillemCastro** [comment]
Implementats a 594c7d295289db8033249f3786e6b061193bdf87 i ef09ac2fc4ed349f1d785667ce5d5810f384a1ee s'ha d'instalar aquest addon al Heroku https://elements.heroku.com/addons/cloudinary (@AleixBalletbo)

Hi ha una instància funcional a https://vast-woodland-58426.herokuapp.com/
